# Generated by Django 4.2.16 on 2024-11-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
