# Generated by Django 4.2.16 on 2024-11-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reblogged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.post'),
        ),
    ]
