# Generated by Django 5.1.3 on 2024-11-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='theranos', max_length=240),
            preserve_default=False,
        ),
    ]
