name: Bug for Project 5
description: A template for issues and bugs for the fifth portfolio project.
title: '[BUG] '
labels: ['bug']
projects: ['DajanPlackovic/4']
assignees:
  - DajanPlackovic
body:
  - type: textarea
    id: bug-description
    attributes:
      label: 'Bug'
      description: Enter a description of the bug or issue
      value: |
        This went super wrong
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: 'Screenshot'
      description: Provide a screenshot of the issue
